# Generated by Django 4.1.7 on 2023-02-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_img",
                    models.ImageField(
                        default="profile_images/default.jpg", upload_to="profile_images"
                    ),
                ),
                ("nickname", models.CharField(max_length=100)),
            ],
        ),
    ]
